DELETE FROM `playercreateinfo_skills` WHERE `raceMask`='0' and`classMask`='32' and`skill`='129';
DELETE FROM `playercreateinfo_skills` WHERE `raceMask`='0' and`classMask`='32' and`skill`='229';
DELETE FROM `playercreateinfo_skills` WHERE `raceMask`='0' and`classMask`='32' and`skill`='293';
DELETE FROM `playercreateinfo_skills` WHERE `raceMask`='0' and`classMask`='32' and`skill`='762';
DELETE FROM `playercreateinfo_skills` WHERE `raceMask`='0' and`classMask`='32' and`skill`='770';
DELETE FROM `playercreateinfo_skills` WHERE `raceMask`='0' and`classMask`='32' and`skill`='771';
DELETE FROM `playercreateinfo_skills` WHERE `raceMask`='0' and`classMask`='32' and`skill`='772';
DELETE FROM `playercreateinfo_skills` WHERE `raceMask`='0' and`classMask`='35' and`skill`='55';
UPDATE `playercreateinfo_skills` SET `raceMask`='0', `classMask`='3' WHERE `raceMask`='0' and`classMask`='35' and`skill`='413';
DELETE FROM `playercreateinfo_skills` WHERE `raceMask`='0' and`classMask`='37' and`skill`='172';
DELETE FROM `playercreateinfo_skills` WHERE `raceMask`='0' and`classMask`='40' and`skill`='118';
DELETE FROM `playercreateinfo_skills` WHERE `raceMask`='1061' and`classMask`='3' and`skill`='160';
UPDATE `playercreateinfo_skills` SET `classMask`='1103' WHERE `raceMask`='0' and`classMask`='1135' and`skill`='414';
UPDATE `playercreateinfo_skills` SET `classMask`='1472' WHERE `raceMask`='0' and`classMask`='1488' and`skill`='136';